"""Generate platform launchers using the env name (active env or environment.yml).

Usage:
    python scripts/make_launcher.py          # auto-detect
    python scripts/make_launcher.py --env-name myenv

Creates/updates:
- run_compress_pdf.cmd (Windows)
- run_compress_pdf.sh  (Linux/macOS)
"""
from __future__ import annotations

import argparse
import os
import sys
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = ROOT / "environment.yml"
LAUNCHER_CMD = ROOT / "run_compress_pdf.cmd"
LAUNCHER_SH = ROOT / "run_compress_pdf.sh"


def detect_env_name(path: Path) -> str | None:
    if not path.exists():
        return None
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"\s*name:\s*([^\s]+)", line)
        if m:
            return m.group(1)
    return None


def detect_active_env() -> str | None:
    return os.environ.get("CONDA_DEFAULT_ENV")


def write_launcher_cmd(env_name: str) -> None:
    content = f"""@echo off
setlocal
rem Auto-generated by scripts/make_launcher.py
set ENV_NAME={env_name}

where conda >nul 2>nul
if errorlevel 1 (
    echo Error: conda not found on PATH.
    echo Add Anaconda/Miniconda to PATH or use an Anaconda prompt.
  exit /b 1
)

call conda activate %ENV_NAME% || (
    echo Unable to activate environment %ENV_NAME%.
    echo Check it exists: conda env list
  exit /b 1
)

compress-pdf %*
"""
    LAUNCHER_CMD.write_text(content, encoding="utf-8")
    print(f"Launcher written to {LAUNCHER_CMD} with env name '{env_name}'")


def write_launcher_sh(env_name: str) -> None:
    content = f"""#!/usr/bin/env bash
set -euo pipefail
# Auto-generated by scripts/make_launcher.py

# Prefer active env, else fallback to provided name
ENV_NAME="${{CONDA_DEFAULT_ENV:-{env_name}}}"

if ! command -v conda >/dev/null 2>&1; then
  echo "Error: conda not found on PATH. Open a shell where conda is available." >&2
  exit 1
fi

# shellcheck disable=SC1091
source "$(conda info --base)/etc/profile.d/conda.sh"

if ! conda activate "$ENV_NAME" >/dev/null 2>&1; then
  echo "Unable to activate environment '$ENV_NAME'. Check with: conda env list" >&2
  exit 1
fi

exec compress-pdf "$@"
"""
    LAUNCHER_SH.write_text(content, encoding="utf-8")
    try:
        LAUNCHER_SH.chmod(LAUNCHER_SH.stat().st_mode | 0o111)
    except Exception:
        pass
    print(f"Launcher written to {LAUNCHER_SH} with env name '{env_name}'")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate run_compress_pdf.cmd")
    parser.add_argument("--env-name", help="Conda environment name to activate")
    args = parser.parse_args()

    env_name = args.env_name or detect_active_env() or detect_env_name(ENV_FILE) or "compress-pdf"
    # Generate only the launcher relevant to the host OS
    if sys.platform.startswith("win"):
        write_launcher_cmd(env_name)
    else:
        write_launcher_sh(env_name)


if __name__ == "__main__":
    main()
